### ISSUE TITLE
Create an Android app - Inspire me

### ISSUE THREAD

**Issue by tapaswenipathak** [tapasweni-pathak/Women-GitHubers#136]
Create an Android app and show one woman on phone screen and their GitHub/open source achievements in a day, the button should say `Inspire me!` 

cc @Siddharth1698.

**Comment by Siddharth1698** [comment]
I got the idea . 
So currently can i use dummy data and display :
 -Woman Photo
 - Github Profile
- Achievement
In one screen 
And this comes when i click on a button in app telling "Inspire me"
Now ill use single persons details.
Is this the idea..?

**Comment by tapaswenipathak** [comment]
Works!

- GitHub API is what should be used though

**Comment by Siddharth1698** [comment]
Yes. I will.. ill make this one for now. And after 10th ill make the one that parses data from github using its api

**Comment by Siddharth1698** [comment]
Hii.. do u have a json file with all the women details . if yes please send me the link.

**Comment by tapaswenipathak** [comment]
On Sat, May 11, 2019 at 11:16 AM Siddharth M <notifications@github.com> wrote:
>
> Hii.. do u have a json file with all the women details . if yes please send me the link.

Please parse the website or you can parse the readme.md as well?
shouldn't be complex.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by Siddharth1698** [comment]
alright

**Comment by Siddharth1698** [comment]
No worries. Ive parsed and created a json from the website. :)
