### ISSUE TITLE
Remove non-active profiles

### ISSUE THREAD

**Issue by Swati4star** [tapasweni-pathak/Women-GitHubers#149]
Some of the profiles in the list are 404 links.
A script in travis (https://travis-ci.org/) using https://github.com/dkhamsing/awesome_bot can be used to check for 404 links.
I can work on this.

**Comment by tapaswenipathak** [comment]
On Wed, 2 Oct 2019, 19:14 Swati Garg, <notifications@github.com> wrote:

> Some of the profiles in the list are 404 links.
> A script in travis (https://travis-ci.org/) using
> https://github.com/dkhamsing/awesome_bot can be used to check for 404
> links.
> I can work on this.
>

Sure.
