### ISSUE TITLE
Sort names alphabetically

### ISSUE THREAD

**Issue by tapaswenipathak** [tapasweni-pathak/Women-GitHubers#23]

**Comment by thefourtheye** [comment]
Isn't it already sorted like that?

**Comment by tapaswenipathak** [comment]
Just check from down, you will get to know. 

I started with things sorted but later people submitted PRs, which were not. I have not mentioned that in the Readme as well.

**Comment by thefourtheye** [comment]
Ah, you are right. I just glanced from the top. Let me see what I can do about it.

**Comment by thefourtheye** [comment]
We can probably have this linked with a CI and fail the PR if the list is not sorted. What do you think?

**Comment by tapaswenipathak** [comment]
@thefourtheye  This will be great. After fixing the current list, that can be done. 

But does CI can check things on the ReadMe as well? I never tried this.

**Comment by thefourtheye** [comment]
@tapasweni-pathak We can configure this project as a Node.js or Python project in CI and we can execute a script which can validate that.

**Comment by thefourtheye** [comment]
@tapasweni-pathak Initial sorting is done and included a note as well. #26

**Comment by tapaswenipathak** [comment]
> We can configure this project as a Node.js or Python project in CI and we can execute a script which can validate that.

@thefourtheye :+1:

**Comment by thefourtheye** [comment]
@tapasweni-pathak I created a basic script and Travis-CI integration file. PTAL at #27

**Comment by PrabhanshuAttri** [comment]
Hey @tapasweni-pathak I have sorted the list and updated it. https://github.com/tapasweni-pathak/Women-GitHubers/pull/54

I have created a script also with it to generate the list automatically. https://women-on-github.herokuapp.com/sorted.php
