### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapasweni-pathak/Women-GitHubers#24]
- Update Readme with more details on how to contribute to the list
- Add a easy way to let people contribute, who can't Git

**Comment by thefourtheye** [comment]
> Update Readme with more details on how to contribute to the list

Yeah, when I told people about this repo, they came back to me with the same question. "The woman who inspired me to code, has done a lot in internal enterprise repos but not much on public repos. Can I include her name as well?" Probably this can be clarified.

> Add a easy way to let people contribute, who can't Git

Do you have any possible solution in your mind?

**Comment by tapaswenipathak** [comment]
> Update Readme with more details on how to contribute to the list
> 
> > Yeah, when I told people about this repo, they came back to me with the same question. "The woman who inspired me to code, has done a lot in internal enterprise repos but not much on public repos. Can I include her name as well?" Probably this can be clarified.

I did not think about this till now. The reason why I started it was to have a list of women who have great GitHub profiles and that the number is not that less.  I want to include these as well but private contributions are not visible to everyone. What do you suggest? 

> Add a easy way to let people contribute, who can't Git
> 
> > Do you have any possible solution in your mind?

Yes, I'm thinking of having a Google Docs Spreadsheet. I can create a script which will pull names from this file and then update the sheet. I'll be creating a project in Google Developers Console to accomplish this.
