### ISSUE TITLE
Be consistent with how accounts are listed

### ISSUE THREAD

**Issue by aviaryan** [tapasweni-pathak/Women-GitHubers#49]
In the README, some accounts are listed by their full name whereas some are listed by their usernames. Please make it uniform.
It would be great if both usernames and full names are there for a user. Something like - 

[tapasweni-pathak](https://github.com/tapasweni-pathak) (Tapasweni Pathak)

**Comment by a2batic** [comment]
I would like to take up this task, please assign this to me.

**Comment by tapaswenipathak** [comment]
@kanikaa1234 You can submit a pull request for this, no need of assigning this. I tried, for some reason your handle is not coming up.

**Comment by aviaryan** [comment]
@tapasweni-pathak Is @kanikaa1234 added as a collaborator ? because that is required to make her assign-able.

**Comment by a2batic** [comment]
I want one suggestion,
[tapasweni-pathak](https://github.com/tapasweni-pathak) (Tapasweni Pathak)
or
Tapasweni Pathak ([tapasweni-pathak](https://github.com/tapasweni-pathak))

Which is better ?
I vote for the second one.

**Comment by tapaswenipathak** [comment]
Second one is fine. :+1:
